import assert from 'node:assert/strict';
import test from 'node:test';
import { execFile, spawn } from 'node:child_process';
import { chmod, mkdir, mkdtemp, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { advancePhase, authorizeAction, bindProcessCandidate, buildCompletedContext, classifyBoundary, createRun, getRun, prepareAction, recordHostEvent, recordPassiveToolObservation, registerHostSession, stableHash } from '../runtime/jev-governance/core.mjs';
import { handleHook } from '../runtime/jev-governance/hook.mjs';

const exec = promisify(execFile);
const cli = fileURLToPath(new URL('../runtime/jev-governance/cli.mjs', import.meta.url));
const route = (role, effort = 'medium') => role === 'coordinator'
  ? { role, provider: 'codex', model: 'gpt-6-sol', reasoning: effort, capabilities: [] }
  : { role, provider: 'codex', model: 'gpt-5.6-luna', reasoning: 'high', capabilities: [] };

test('phase effort change waits for a later exact host handoff and preserves acceptance epoch', { timeout: 30000 }, async (t) => {
  const base = await realpath(await mkdtemp(join(tmpdir(), 'governance-effort-')));
  t.after(() => rm(base, { recursive: true, force: true }));
  const home = join(base, 'home'), root = join(base, 'root'), transcript = join(base, 'transcript.jsonl'), session = 'effort-session';
  await mkdir(home); await mkdir(root); await writeFile(join(root, 'spec.md'), 'C1: research current source.\n');
  await exec('git', ['init', '-q', root]); await exec('git', ['add', '.'], { cwd: root });
  await exec('git', ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '-qm', 'base'], { cwd: root });
  const sha = (await exec('git', ['rev-parse', 'HEAD'], { cwd: root })).stdout.trim();
  const provider = join(base, 'fixture-provider');
  await writeFile(provider, '#!/usr/bin/env node\nprocess.stdout.write("Observed research return.");\n'); await chmod(provider, 0o700);
  await registerHostSession({ home, event: { kind: 'session', sessionId: session, model: 'gpt-6-sol', reasoning: 'medium', cwd: root, transcriptPath: transcript } });
  const passive = { session_id: session, turn_id: 'passive', tool_use_id: 'pwd', model: 'gpt-6-sol', reasoning: 'medium', cwd: root, tool_name: 'Bash', tool_input: { command: 'pwd' } };
  await recordPassiveToolObservation({ home, event: { ...passive, hook_event_name: 'PreToolUse' } });
  await recordPassiveToolObservation({ home, event: { ...passive, hook_event_name: 'PostToolUse', tool_response: { exit_code: 0, stdout: root } } });
  await createRun({ home, contract: { id: 'effort-run', root, baseSha: sha, endpoint: 'local accepted', authorization: 'Research and confirm the isolated phase transition.', sources: [{ id: 'spec', path: 'spec.md', kind: 'spec' }], tickets: [{ id: 'T1', dependsOn: [] }], criteria: [{ id: 'C1', ticketId: 'T1', requirement: 'Research source', evidenceRequired: 'Observed return' }], capacity: { total: 2, providers: { codex: 2 } }, requiredCapabilities: ['shell'] }, activation: { sessionId: session } });
  const runDirectory = join(home, '.development-system/governance/runs/effort-run');
  const transport = async ({ body }) => {
    const request = JSON.parse(body), answers = {};
    for (const [key, question] of Object.entries(request.questions)) {
      const labels = Object.keys(question.criteria), choice = key === 'route' ? request.state.boundary.route.role : key === 'tool' ? 'compliant' : key === 'priority' ? 'execute_now' : 'satisfied';
      answers[key] = { type: 'choice', choice, confidence: 1, probabilities: Object.fromEntries(labels.map(label => [label, label === choice ? 1 : 0])) };
    }
    return { model: 'jev-1.13.0', usage: { input_tokens: 1, output_tokens: 1 }, answers };
  };
  const classify = async (id, phase, action, options = {}) => {
    const proposal = { id, phase, action, actorId: session, attemptId: null, objective: `Perform ${action} for C1.`, requirementIds: ['C1'], sourceIds: ['spec'], readSet: ['spec.md'], writeSet: [], dependsOn: [], route: route('coordinator'), toolName: 'governance', toolInput: {}, evidenceRefs: [], observations: ['Research is within the authorized local endpoint.'], ...options };
    const judgment = await classifyBoundary({ runDirectory, proposal, transport, env: { TYPESAFE_API_KEY: 'fixture-only' } });
    assert.equal(judgment.verdict, 'pass', judgment.reason);
    return proposal;
  };
  const intake = await classify('intake', 'intake', 'intake-review');
  await advancePhase({ runDirectory, transition: { to: 'research', reason: 'Intake passed', boundaryId: intake.id } });
  const launch = { attemptId: 'research-attempt' };
  const command = `node '${cli}' execute --home '${home}' --input-json '${JSON.stringify(launch)}'`;
  const dispatch = await classify('research-dispatch', 'research', 'research-dispatch', { attemptId: launch.attemptId, route: route('researcher'), toolName: 'Bash', toolInput: { command } });
  await prepareAction({ runDirectory, boundaryId: dispatch.id, action: { actorId: session, attemptId: launch.attemptId, toolName: 'Bash', toolInput: { command } } });
  const toolEvent = { session_id: session, turn_id: 'research-turn', tool_use_id: 'research-tool', hook_event_name: 'PreToolUse', model: 'gpt-6-sol', reasoning: 'medium', cwd: root, tool_name: 'Bash', tool_input: { command } };
  assert.equal((await authorizeAction({ home, preToolEvent: toolEvent })).decision, 'allow');
  const childCommand = { executable: provider, argv: ['exec', '--model', 'gpt-5.6-luna', '--sandbox', 'read-only', '-c', 'model_reasoning_effort="high"'] };
  await bindProcessCandidate({ runDirectory, attemptId: launch.attemptId, candidateRoot: root, command: childCommand });
  const child = spawn(childCommand.executable, childCommand.argv, { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = ''; child.stdout.on('data', chunk => { output += chunk; }); child.stderr.resume();
  const exitCode = await new Promise((done, reject) => { child.on('error', reject); child.on('close', done); });
  const common = { attemptId: launch.attemptId, processId: String(child.pid), candidateRoot: root, command: childCommand };
  assert.equal((await recordHostEvent({ home, event: { kind: 'process-start', ...common, provider: 'unknown', model: 'unknown', reasoning: 'unknown' } })).status, 'identity-pending');
  assert.equal((await recordHostEvent({ home, event: { kind: 'process-exit', ...common, provider: 'codex', model: 'gpt-5.6-luna', reasoning: 'high', processSessionId: 'research-child', exitCode, terminated: true, output, changedPaths: [] } })).status, 'awaiting-post');
  await recordHostEvent({ home, event: { kind: 'hook', sessionId: session, hookEventName: 'PostToolUse', turnId: toolEvent.turn_id, toolUseId: toolEvent.tool_use_id, toolName: 'Bash', toolInput: { command }, output: { exit_code: 0 }, cwd: root, model: 'gpt-6-sol', reasoning: 'medium' } });
  const change = { sessionId: session, provider: 'codex', model: 'gpt-6-sol', oldEffort: 'medium', newEffort: 'low', to: 'plan' };
  const returned = await classify('research-return', 'research', 'research-return', { dependsOn: [launch.attemptId], coordinatorEffortTransition: change });
  const transition = { to: 'plan', reason: 'Observed research return', boundaryId: returned.id, coordinatorEffortTransition: change };
  const control = (operation, input) => `node '${cli}' ${operation} --home '${home}' --input-json '${JSON.stringify(input)}' --json`;
  const transcriptLine = (type, payload) => JSON.stringify({ type, payload });
  const sessionMeta = transcriptLine('session_meta', { id: session });
  const turn = (id, effort) => transcriptLine('turn_context', { turn_id: id, model: 'gpt-6-sol', cwd: root, effort });
  await writeFile(transcript, `${sessionMeta}\n${turn('advance-turn', 'medium')}\n`);
  const hook = (turnId, toolUseId, effort, cmd) => ({ session_id: session, turn_id: turnId, tool_use_id: toolUseId, hook_event_name: 'PreToolUse', transcript_path: transcript, model: 'gpt-6-sol', cwd: root, tool_name: 'Bash', tool_input: { command: cmd } });
  const advanceCommand = control('advance', transition);
  await assert.rejects(exec(process.execPath, [cli, 'advance', '--home', home, '--input-json', JSON.stringify(transition), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } }));
  assert.deepEqual(await handleHook(hook('advance-turn', 'advance-tool', 'medium', advanceCommand), { home }), {});
  assert.equal((await exec(process.execPath, [cli, 'advance', '--home', home, '--input-json', JSON.stringify(transition), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } })).stdout.includes('"pendingCoordinatorEffortTransition"'), true);
  const pending = await getRun({ runDirectory });
  assert.equal(pending.phase, 'research'); assert.equal(pending.acceptanceEpoch, 0);
  for (let stop = 0; stop < 4; stop += 1) {
    assert.deepEqual(await handleHook({ session_id: session, turn_id: 'advance-turn', hook_event_name: 'Stop', transcript_path: transcript, model: 'gpt-6-sol', cwd: root }, { home }), {});
  }
  assert.deepEqual(await getRun({ runDirectory }), pending, 'ending the handoff turn grants no phase or acceptance and does not close the run');
  assert.equal((await authorizeAction({ home, preToolEvent: toolEvent })).decision, 'deny');
  const confirmation = { transitionHash: stableHash(change) };
  const confirmCommand = control('confirm-effort', confirmation);
  await assert.rejects(exec(process.execPath, [cli, 'confirm-effort', '--home', home, '--input-json', JSON.stringify(confirmation), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } }));
  await writeFile(transcript, `${sessionMeta}\n${turn('advance-turn', 'medium')}\n${turn('confirm-turn', 'low')}\n`);
  assert.equal((await handleHook(hook('advance-turn', 'same-turn', 'low', confirmCommand), { home })).hookSpecificOutput.permissionDecision, 'deny');
  assert.equal((await handleHook({ ...hook('confirm-turn', 'wrong-model', 'low', confirmCommand), model: 'gpt-6-astra' }, { home })).hookSpecificOutput.permissionDecision, 'deny');
  assert.equal((await handleHook({ ...hook('confirm-turn', 'wrong-root', 'low', confirmCommand), cwd: base }, { home })).hookSpecificOutput.permissionDecision, 'deny');
  assert.equal((await handleHook({ ...hook('confirm-turn', 'wrong-session', 'low', confirmCommand), session_id: 'different-session' }, { home })).hookSpecificOutput.permissionDecision, 'deny');
  assert.equal((await handleHook({ ...hook('confirm-turn', 'wrong-tool', 'low', confirmCommand), tool_name: 'mcp__linear__get_issue' }, { home })).hookSpecificOutput.permissionDecision, 'deny');
  await writeFile(transcript, `${sessionMeta}\n${turn('advance-turn', 'medium')}\n${turn('medium-turn', 'medium')}\n${turn('confirm-turn', 'low')}\n`);
  assert.equal((await handleHook(hook('medium-turn', 'wrong-effort', 'medium', confirmCommand), { home })).hookSpecificOutput.permissionDecision, 'deny');
  assert.deepEqual(await handleHook(hook('confirm-turn', 'confirm-tool', 'low', confirmCommand), { home }), {});
  await writeFile(join(root, 'spec.md'), 'C1 changed after the accepted return.\n');
  await assert.rejects(exec(process.execPath, [cli, 'confirm-effort', '--home', home, '--input-json', JSON.stringify(confirmation), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } }));
  assert.equal((await getRun({ runDirectory })).phase, 'research');
  await writeFile(join(root, 'spec.md'), 'C1: research current source.\n');
  await assert.rejects(exec(process.execPath, [cli, 'confirm-effort', '--home', home, '--input-json', JSON.stringify(confirmation), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } }), 'the rejected handoff remains consumed');
  await writeFile(transcript, `${sessionMeta}\n${turn('advance-turn', 'medium')}\n${turn('medium-turn', 'medium')}\n${turn('confirm-turn', 'low')}\n${turn('retry-turn', 'low')}\n`);
  assert.deepEqual(await handleHook(hook('retry-turn', 'retry-tool', 'low', confirmCommand), { home }), {});
  const confirmed = await exec(process.execPath, [cli, 'confirm-effort', '--home', home, '--input-json', JSON.stringify(confirmation), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } });
  assert.equal(JSON.parse(confirmed.stdout).phase, 'plan');
  const done = await getRun({ runDirectory });
  assert.equal(done.coordinator.reasoning, 'low'); assert.equal(done.coordinatorIdentityEpoch, 1); assert.equal(done.acceptanceEpoch, 0);
  await assert.rejects(exec(process.execPath, [cli, 'confirm-effort', '--home', home, '--input-json', JSON.stringify(confirmation), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } }));
  const next = await classify('next-inspect', 'plan', 'inspect', { route: route('coordinator', 'low'), toolName: 'Bash', toolInput: { command: 'pwd' } });
  await prepareAction({ runDirectory, boundaryId: next.id, action: { actorId: session, attemptId: null, toolName: 'Bash', toolInput: { command: 'pwd' } } });
  await writeFile(transcript, `${sessionMeta}\n${turn('advance-turn', 'medium')}\n${turn('medium-turn', 'medium')}\n${turn('confirm-turn', 'low')}\n${turn('retry-turn', 'low')}\n${turn('next-turn', 'low')}\n`);
  assert.deepEqual(await handleHook(hook('next-turn', 'next-tool', 'low', 'pwd'), { home }), {});
});

test('audit effort transitions retain current plan and final review artifacts', { timeout: 45000 }, async (t) => {
  const base = await realpath(await mkdtemp(join(tmpdir(), 'governance-effort-audit-')));
  t.after(() => rm(base, { recursive: true, force: true }));
  const home = join(base, 'home'), root = join(base, 'root'), transcript = join(base, 'transcript.jsonl'), session = 'audit-effort-session';
  await mkdir(home); await mkdir(root); await writeFile(join(root, 'spec.md'), 'C1: inspect and assess the unchanged source.\n');
  await exec('git', ['init', '-q', root]); await exec('git', ['add', '.'], { cwd: root });
  await exec('git', ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '-qm', 'base'], { cwd: root });
  const sha = (await exec('git', ['rev-parse', 'HEAD'], { cwd: root })).stdout.trim();
  const provider = join(base, 'fixture-provider');
  await writeFile(provider, '#!/usr/bin/env node\nprocess.stdout.write(process.env.FIXTURE_OUTPUT ?? "Observed fixture return.");\n'); await chmod(provider, 0o700);
  await registerHostSession({ home, event: { kind: 'session', sessionId: session, model: 'gpt-6-sol', reasoning: 'medium', cwd: root, transcriptPath: transcript } });
  const passive = { session_id: session, turn_id: 'passive', tool_use_id: 'pwd', model: 'gpt-6-sol', reasoning: 'medium', cwd: root, tool_name: 'Bash', tool_input: { command: 'pwd' } };
  await recordPassiveToolObservation({ home, event: { ...passive, hook_event_name: 'PreToolUse' } });
  await recordPassiveToolObservation({ home, event: { ...passive, hook_event_name: 'PostToolUse', tool_response: { exit_code: 0, stdout: root } } });
  await createRun({ home, contract: { id: 'audit-effort', root, baseSha: sha, endpoint: 'local accepted', taskKind: 'audit', authorization: 'Audit unchanged local source and retain current reviews.', sources: [{ id: 'spec', path: 'spec.md', kind: 'spec' }], tickets: [{ id: 'T1', dependsOn: [] }], criteria: [{ id: 'C1', ticketId: 'T1', requirement: 'Assess source', evidenceRequired: 'Current independent review' }], capacity: { total: 2, providers: { codex: 2 } }, requiredCapabilities: ['shell'] }, activation: { sessionId: session } });
  const runDirectory = join(home, '.development-system/governance/runs/audit-effort');
  const transport = async ({ body }) => {
    const request = JSON.parse(body), answers = {};
    for (const [key, question] of Object.entries(request.questions)) {
      const labels = Object.keys(question.criteria), choice = key === 'route' ? request.state.boundary.route.role : key === 'tool' ? 'compliant' : key === 'priority' ? 'execute_now' : 'satisfied';
      answers[key] = { type: 'choice', choice, confidence: 1, probabilities: Object.fromEntries(labels.map(label => [label, label === choice ? 1 : 0])) };
    }
    return { model: 'jev-1.13.0', usage: { input_tokens: 1, output_tokens: 1 }, answers };
  };
  let effort = 'medium';
  const roleRoute = role => role === 'coordinator' ? route(role, effort) : role === 'researcher' ? route(role) : { role, provider: 'codex', model: 'gpt-6-astra', reasoning: 'xhigh', capabilities: [] };
  const classify = async (id, action, options = {}) => {
    const run = await getRun({ runDirectory });
    const proposal = { id, phase: run.phase, action, actorId: session, attemptId: null, objective: `Complete ${action} for C1.`, requirementIds: ['C1'], sourceIds: ['spec'], readSet: ['spec.md'], writeSet: [], dependsOn: [], route: roleRoute('coordinator'), toolName: 'governance', toolInput: {}, evidenceRefs: [], observations: ['The audit remains within the local endpoint.'], ...options };
    const judgment = await classifyBoundary({ runDirectory, proposal, transport, env: { TYPESAFE_API_KEY: 'fixture-only' } });
    assert.equal(judgment.verdict, 'pass', `${id}: ${judgment.reason}`);
    return proposal;
  };
  let toolNumber = 0;
  const dispatch = async (id, action, role, output) => {
    const launch = { attemptId: id };
    const command = `node '${cli}' execute --home '${home}' --input-json '${JSON.stringify(launch)}'`;
    const proposal = await classify(`${id}-dispatch`, action, { attemptId: id, route: roleRoute(role), toolName: 'Bash', toolInput: { command } });
    await prepareAction({ runDirectory, boundaryId: proposal.id, action: { actorId: session, attemptId: id, toolName: 'Bash', toolInput: { command } } });
    toolNumber += 1;
    const turnId = `dispatch-turn-${toolNumber}`, toolUseId = `dispatch-tool-${toolNumber}`;
    assert.equal((await authorizeAction({ home, preToolEvent: { session_id: session, turn_id: turnId, tool_use_id: toolUseId, hook_event_name: 'PreToolUse', model: 'gpt-6-sol', reasoning: effort, cwd: root, tool_name: 'Bash', tool_input: { command } } })).decision, 'allow');
    const profile = roleRoute(role);
    const childCommand = { executable: provider, argv: ['exec', '--model', profile.model, '--sandbox', 'read-only', '-c', `model_reasoning_effort="${profile.reasoning}"`] };
    await bindProcessCandidate({ runDirectory, attemptId: id, candidateRoot: root, command: childCommand });
    const child = spawn(childCommand.executable, childCommand.argv, { cwd: root, env: { ...process.env, FIXTURE_OUTPUT: typeof output === 'string' ? output : JSON.stringify(output) }, stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = ''; child.stdout.on('data', chunk => { stdout += chunk; }); child.stderr.resume();
    const exitCode = await new Promise((done, reject) => { child.on('error', reject); child.on('close', done); });
    const common = { attemptId: id, processId: String(child.pid), candidateRoot: root, command: childCommand };
    assert.equal((await recordHostEvent({ home, event: { kind: 'process-start', ...common, provider: 'unknown', model: 'unknown', reasoning: 'unknown' } })).status, 'identity-pending');
    assert.equal((await recordHostEvent({ home, event: { kind: 'process-exit', ...common, provider: 'codex', model: profile.model, reasoning: profile.reasoning, processSessionId: `fresh-${id}`, exitCode, terminated: true, output: stdout, changedPaths: [] } })).status, 'awaiting-post');
    assert.equal((await recordHostEvent({ home, event: { kind: 'hook', sessionId: session, hookEventName: 'PostToolUse', turnId, toolUseId, toolName: 'Bash', toolInput: { command }, output: { exit_code: 0 }, cwd: root, model: 'gpt-6-sol', reasoning: effort } })).status, 'completed');
    return id;
  };
  const plainAdvance = async (action, to, dependency) => {
    const returned = await classify(`${action}-boundary`, action, { dependsOn: [dependency] });
    await advancePhase({ runDirectory, transition: { to, reason: `Observed ${action}`, boundaryId: returned.id } });
  };
  const sessionMeta = JSON.stringify({ type: 'session_meta', payload: { id: session } });
  const turn = (id, currentEffort) => JSON.stringify({ type: 'turn_context', payload: { turn_id: id, model: 'gpt-6-sol', cwd: root, effort: currentEffort } });
  const turns = [];
  const control = (operation, input) => `node '${cli}' ${operation} --home '${home}' --input-json '${JSON.stringify(input)}' --json`;
  const confirmPhase = async (action, to, dependency, nextEffort, label) => {
    const change = { sessionId: session, provider: 'codex', model: 'gpt-6-sol', oldEffort: effort, newEffort: nextEffort, to };
    const returned = await classify(`${action}-${label}`, action, { dependsOn: [dependency], coordinatorEffortTransition: change });
    const transition = { to, reason: `Observed ${action}`, boundaryId: returned.id, coordinatorEffortTransition: change };
    const advanceTurn = `${label}-advance`, confirmTurn = `${label}-confirm`;
    turns.push(turn(advanceTurn, effort)); await writeFile(transcript, `${sessionMeta}\n${turns.join('\n')}\n`);
    const advanceCommand = control('advance', transition);
    assert.deepEqual(await handleHook({ session_id: session, turn_id: advanceTurn, tool_use_id: `${label}-advance-tool`, hook_event_name: 'PreToolUse', transcript_path: transcript, model: 'gpt-6-sol', cwd: root, tool_name: 'Bash', tool_input: { command: advanceCommand } }, { home }), {});
    await exec(process.execPath, [cli, 'advance', '--home', home, '--input-json', JSON.stringify(transition), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } });
    turns.push(turn(confirmTurn, nextEffort)); await writeFile(transcript, `${sessionMeta}\n${turns.join('\n')}\n`);
    const confirmation = { transitionHash: stableHash(change) }, confirmCommand = control('confirm-effort', confirmation);
    assert.deepEqual(await handleHook({ session_id: session, turn_id: confirmTurn, tool_use_id: `${label}-confirm-tool`, hook_event_name: 'PreToolUse', transcript_path: transcript, model: 'gpt-6-sol', cwd: root, tool_name: 'Bash', tool_input: { command: confirmCommand } }, { home }), {});
    const confirmed = await exec(process.execPath, [cli, 'confirm-effort', '--home', home, '--input-json', JSON.stringify(confirmation), '--json'], { env: { ...process.env, CODEX_THREAD_ID: session } });
    assert.equal(JSON.parse(confirmed.stdout).phase, to);
    effort = nextEffort;
  };
  const intake = await classify('audit-intake', 'intake-review');
  await advancePhase({ runDirectory, transition: { to: 'research', reason: 'Intake passed', boundaryId: intake.id } });
  await dispatch('audit-research', 'research-dispatch', 'researcher', 'Observed audit source.');
  await plainAdvance('research-return', 'plan', 'audit-research');
  await dispatch('audit-plan', 'plan-author', 'planner', { kind: 'plan', summary: 'Review the unchanged source.', criterionIds: ['C1'], packets: [{ id: 'P1', readSet: ['spec.md'], writeSet: [], dependsOn: [] }] });
  await plainAdvance('plan-return', 'plan-review', 'audit-plan');
  await dispatch('audit-plan-review', 'plan-review', 'plan-reviewer', { kind: 'review', verdict: 'pass', findings: [], criterionIds: ['C1'] });
  const beforeAuditTransition = await getRun({ runDirectory });
  assert.equal(beforeAuditTransition.reviews.at(-1).kind, 'plan-review');
  await confirmPhase('plan-review-return', 'final-review', 'audit-plan-review', 'low', 'audit');
  const afterAuditTransition = await getRun({ runDirectory });
  assert.equal(afterAuditTransition.phase, 'final-review');
  assert.equal(afterAuditTransition.acceptanceEpoch, beforeAuditTransition.acceptanceEpoch);
  await dispatch('audit-final-review', 'final-review', 'reviewer', { kind: 'review', verdict: 'pass', findings: [], criterionIds: ['C1'] });
  const beforeEvidence = await getRun({ runDirectory });
  const finalReview = beforeEvidence.reviews.at(-1);
  assert.equal(finalReview.kind, 'final-review'); assert.equal(finalReview.verdict, 'pass');
  await confirmPhase('final-review-return', 'evidence', 'audit-final-review', 'medium', 'evidence');
  const afterEvidence = await getRun({ runDirectory });
  assert.equal(afterEvidence.phase, 'evidence');
  assert.equal(afterEvidence.acceptanceEpoch, beforeEvidence.acceptanceEpoch);
  assert.equal(afterEvidence.reviews.at(-1).id, finalReview.id);
  assert.equal(afterEvidence.reviews.at(-1).invalidated, undefined);
  assert.equal(afterEvidence.coordinatorEffortReceipts.length, 2);
  // Current final review is a real prerequisite after the effort-only transition.
  const evidenceContext = await classify('audit-evidence-inspect', 'inspect', { route: route('coordinator', effort), toolName: 'Bash', toolInput: { command: 'pwd' } });
  assert.equal(evidenceContext.phase, 'evidence');
  const completed = await buildCompletedContext(afterEvidence, evidenceContext);
  assert.equal(completed.reviews.find(review => review.id === finalReview.id).current, true);
});
